/* eslint-disable @typescript-eslint/no-explicit-any */
export const endpoints: string[] = [
  'login',
  'logout',
  'register',
  'account',
  'chat',
  'products',
  'orders',
  'posts',
  'admin',
]

export enum SHIPPING_STATUS {
  Pending = 'Pending',
  Shipped = 'Shipped',
  Delivered = 'Delivered',
}

export const provinces: any[] = [
  { label: 'An Giang', value: 'AG' },
  { label: 'Ba Ria - Vung Tau', value: 'BR-VT' },
  { label: 'Bac Giang', value: 'BG' },
  { label: 'Bac Kan', value: 'BK' },
  { label: 'Bac Lieu', value: 'BL' },
  { label: 'Bac Ninh', value: 'BN' },
  { label: 'Ben Tre', value: 'BTR' },
  { label: 'Binh Duong', value: 'BDUOG' },
  { label: 'Binh Dinh', value: 'BDINH' },
  { label: 'Binh Phuoc', value: 'BP' },
  { label: 'Binh Thuan', value: 'BTN' },
  { label: 'Ca Mau', value: 'CM' },
  { label: 'Can Tho', value: 'CT' },
  { label: 'Cao Bang', value: 'CB' },
  { label: 'Da Nang', value: 'DN' },
  { label: 'Dak Lak', value: 'DALAT' },
  { label: 'Dak Nong', value: 'DNONG' },
  { label: 'Dien Bien', value: 'DBIEN' },
  { label: 'Dong Nai', value: 'DNAI' },
  { label: 'Dong Thap', value: 'DTHAP' },
  { label: 'Gia Lai', value: 'GL' },
  { label: 'Ha Giang', value: 'HAG' },
  { label: 'Ha Nam', value: 'HAN' },
  { label: 'Ha Noi', value: 'HN' },
  { label: 'Ha Tinh', value: 'HT' },
  { label: 'Hai Duong', value: 'HD' },
  { label: 'Hai Phong', value: 'HP' },
  { label: 'Hau Giang', value: 'HGI' },
  { label: 'Hoa Binh', value: 'HB' },
  { label: 'Ho Chi Minh', value: 'HCM' },
  { label: 'Hung Yen', value: 'HY' },
  { label: 'Khanh Hoa', value: 'KH' },
  { label: 'Kien Giang', value: 'KG' },
  { label: 'Kon Tum', value: 'KT' },
  { label: 'Lai Chau', value: 'LCH' },
  { label: 'Lam Dong', value: 'LD' },
  { label: 'Lang Son', value: 'LS' },
  { label: 'Lao Cai', value: 'LCA' },
  { label: 'Long An', value: 'LA' },
  { label: 'Nam Dinh', value: 'NAMD' },
  { label: 'Nghe An', value: 'NA' },
  { label: 'Ninh Binh', value: 'NB' },
  { label: 'Ninh Thuan', value: 'NT' },
  { label: 'Phu Tho', value: 'PT' },
  { label: 'Phu Yen', value: 'PY' },
  { label: 'Quang Binh', value: 'QB' },
  { label: 'Quang Nam', value: 'QNA' },
  { label: 'Quang Ngai', value: 'QNg' },
  { label: 'Quang Ninh', value: 'QNI' },
  { label: 'Quang Tri', value: 'QT' },
  { label: 'Soc Trang', value: 'ST' },
  { label: 'Son La', value: 'SL' },
  { label: 'Tay Ninh', value: 'TNINH' },
  { label: 'Thai Binh', value: 'TB' },
  { label: 'Thai Nguyen', value: 'TNG' },
  { label: 'Thanh Hoa', value: 'TH' },
  { label: 'Thua Thien-Hue', value: 'TTH' },
  { label: 'Tien Giang', value: 'TG' },
  { label: 'Tra Vinh', value: 'TV' },
  { label: 'Tuyen Quang', value: 'TQ' },
  { label: 'Vinh Long', value: 'VL' },
  { label: 'Vinh Phuc', value: 'VP' },
  { label: 'Yen Bai', value: 'YB' },
]
